<?php

/* remove the opening php tag before importing */

array(
  (object) array(
      'vid' => '10441',
      'uid' => '8',
      'title' => 'Training Department Local Install IT Request',
      'status' => '1',
      'comment' => '1',
      'promote' => '0',
      'sticky' => '0',
      'vuuid' => '62edd37b-ddc6-a134-55b4-35391d2b39cc',
      'nid' => '9782',
      'type' => 'webform',
      'language' => 'und',
      'created' => '1367516677',
      'changed' => 1367519534,
      'tnid' => '0',
      'translate' => '0',
      'uuid' => '94d84eba-f2ef-1b44-b540-245b36d1a77b',
      'revision_timestamp' => '1367517150',
      'revision_uid' => '8',
      'taxonomy_vocabulary_5' => array(
        'und' => array(
          array(
            'tid' => '71',
          ),
        ),
      ),
      'body' => array(
        'und' => array(
          array(
            'value' => "<p>Testing this. &nbsp;Will be a form for trainers to request help if they have problems with the local eCW install on their laptop/tablet</p>\r\n",
            'summary' => '',
            'format' => '2',
            'safe_value' => "<p>Testing this. &nbsp;Will be a form for trainers to request help if they have problems with the local eCW install on their laptop/tablet</p>\n",
            'safe_summary' => '',
          ),
        ),
      ),
      'upload' => array(),
      'webform' => array(
        'nid' => '9782',
        'confirmation' => "<h3>\r\n\tThank you for submitting your request. &nbsp;</h3>\r\n<h3>\r\n\tSomeone will be in touch with your shortly. &nbsp;</h3>\r\n",
        'confirmation_format' => '2',
        'redirect_url' => '<confirmation>',
        'status' => '1',
        'block' => '0',
        'teaser' => '0',
        'allow_draft' => '0',
        'auto_save' => '1',
        'submit_notice' => '1',
        'submit_text' => '',
        'submit_limit' => '-1',
        'submit_interval' => '-1',
        'total_submit_limit' => '-1',
        'total_submit_interval' => '-1',
        'record_exists' => TRUE,
        'roles' => array(
          '3',
          '5',
        ),
        'emails' => array(
          1 => array(
            'nid' => '9782',
            'eid' => '1',
            'email' => 'emailaddressgoeshere',
            'subject' => 'default',
            'from_name' => 'default',
            'from_address' => 'default',
            'template' => 'default',
            'excluded_components' => array(),
            'html' => '0',
            'attachments' => '0',
          ),
        ),
        'components' => array(
          1 => array(
            'nid' => 9782,
            'cid' => '1',
            'pid' => '0',
            'form_key' => 'tr_first_name',
            'name' => 'Please Enter your First Name',
            'type' => 'textfield',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'disabled' => 0,
              'unique' => 0,
              'conditional_operator' => '=',
              'width' => '',
              'maxlength' => '',
              'field_prefix' => '',
              'field_suffix' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '1',
            'weight' => '0',
            'page_num' => 1,
          ),
          2 => array(
            'nid' => 9782,
            'cid' => '2',
            'pid' => '0',
            'form_key' => 'tr_last_name',
            'name' => 'Please Enter your Last Name',
            'type' => 'textfield',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'disabled' => 0,
              'unique' => 0,
              'conditional_operator' => '=',
              'width' => '',
              'maxlength' => '',
              'field_prefix' => '',
              'field_suffix' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '1',
            'weight' => '1',
            'page_num' => 1,
          ),
          3 => array(
            'nid' => 9782,
            'cid' => '3',
            'pid' => '0',
            'form_key' => 'best_call_back_',
            'name' => 'Best Call Back #',
            'type' => 'textfield',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'disabled' => 0,
              'unique' => 0,
              'conditional_operator' => '=',
              'width' => '',
              'maxlength' => '',
              'field_prefix' => '',
              'field_suffix' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '1',
            'weight' => '2',
            'page_num' => 1,
          ),
          14 => array(
            'nid' => 9782,
            'cid' => '14',
            'pid' => '0',
            'form_key' => 'email',
            'name' => 'Email',
            'type' => 'email',
            'value' => '%useremail',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'disabled' => 0,
              'unique' => 0,
              'conditional_component' => '1',
              'conditional_operator' => '=',
              'width' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_values' => '',
            ),
            'mandatory' => '1',
            'weight' => '3',
            'page_num' => 1,
          ),
          6 => array(
            'nid' => 9782,
            'cid' => '6',
            'pid' => '0',
            'form_key' => 'your_location',
            'name' => 'Your Location',
            'type' => 'textfield',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'disabled' => 0,
              'unique' => 0,
              'conditional_operator' => '=',
              'width' => '',
              'maxlength' => '',
              'field_prefix' => '',
              'field_suffix' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '0',
            'weight' => '4',
            'page_num' => 1,
          ),
          4 => array(
            'nid' => 9782,
            'cid' => '4',
            'pid' => '0',
            'form_key' => 'subject',
            'name' => 'Subject',
            'type' => 'textfield',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'disabled' => 0,
              'unique' => 0,
              'conditional_operator' => '=',
              'width' => '',
              'maxlength' => '',
              'field_prefix' => '',
              'field_suffix' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '1',
            'weight' => '5',
            'page_num' => 1,
          ),
          5 => array(
            'nid' => 9782,
            'cid' => '5',
            'pid' => '0',
            'form_key' => 'please_select_the_nature_of_your_problem',
            'name' => 'Please Select the Nature of your Problem',
            'type' => 'select',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'aslist' => 0,
              'optrand' => 0,
              'conditional_operator' => '=',
              'other_option' => 0,
              'other_text' => 'Other...',
              'items' => "1|Login Problem\n2|Front Office\n3|EMR\n4|Billing\n5|Add-on Features\n",
              'multiple' => 0,
              'custom_keys' => 0,
              'description' => '',
              'options_source' => '',
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '1',
            'weight' => '6',
            'page_num' => 1,
          ),
          7 => array(
            'nid' => 9782,
            'cid' => '7',
            'pid' => '0',
            'form_key' => 'page_2',
            'name' => 'Page 2',
            'type' => 'pagebreak',
            'value' => '',
            'extra' => array(
              'conditional_operator' => '=',
              'private' => 0,
              'next_page_label' => '',
              'prev_page_label' => '',
              'conditional_component' => '',
              'conditional_values' => '',
            ),
            'mandatory' => '0',
            'weight' => '7',
            'page_num' => 2,
          ),
          8 => array(
            'nid' => 9782,
            'cid' => '8',
            'pid' => '0',
            'form_key' => 'please_select_a_login_problem',
            'name' => 'Please Select a Login Problem',
            'type' => 'select',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'aslist' => 0,
              'optrand' => 0,
              'conditional_component' => '5',
              'conditional_operator' => '=',
              'conditional_values' => '1',
              'other_option' => 1,
              'other_text' => 'Other...',
              'items' => "1|Locked Out\n2|Server Error\n3|Password\n",
              'multiple' => 0,
              'custom_keys' => 0,
              'description' => '',
              'options_source' => '',
            ),
            'mandatory' => '1',
            'weight' => '8',
            'page_num' => 2,
          ),
          9 => array(
            'nid' => 9782,
            'cid' => '9',
            'pid' => '0',
            'form_key' => 'please_select_a_front_office_problem',
            'name' => 'Please Select a Front Office Problem',
            'type' => 'select',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'aslist' => 0,
              'optrand' => 0,
              'conditional_component' => '5',
              'conditional_operator' => '=',
              'conditional_values' => '2',
              'other_option' => 1,
              'other_text' => 'Other...',
              'items' => "1|Appointments/Schedule\n2|Demographics\n3|Documents\n4|Letters\n",
              'multiple' => 0,
              'custom_keys' => 0,
              'description' => '',
              'options_source' => '',
            ),
            'mandatory' => '1',
            'weight' => '9',
            'page_num' => 2,
          ),
          10 => array(
            'nid' => 9782,
            'cid' => '10',
            'pid' => '0',
            'form_key' => 'emr_problem',
            'name' => 'Please Select an EMR Problem',
            'type' => 'select',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'aslist' => 0,
              'optrand' => 0,
              'conditional_component' => '5',
              'conditional_operator' => '=',
              'conditional_values' => '3',
              'other_option' => 1,
              'other_text' => 'Other...',
              'items' => "1|Progress Note Customization\n2|Progress Note Functionality\n3|Registry\n4|Logs\n",
              'multiple' => 0,
              'custom_keys' => 0,
              'description' => '',
              'options_source' => '',
            ),
            'mandatory' => '1',
            'weight' => '10',
            'page_num' => 2,
          ),
          12 => array(
            'nid' => 9782,
            'cid' => '12',
            'pid' => '0',
            'form_key' => 'billing_problem',
            'name' => 'Please Select a Billing Problem',
            'type' => 'select',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'aslist' => 0,
              'optrand' => 0,
              'conditional_component' => '5',
              'conditional_operator' => '=',
              'conditional_values' => '4',
              'other_option' => 1,
              'other_text' => 'Other...',
              'items' => "1|Configuration\n2|Encounters/Claims\n3|Payments\n4|Statements/Collections\n",
              'multiple' => 0,
              'custom_keys' => 0,
              'description' => '',
              'options_source' => '',
            ),
            'mandatory' => '1',
            'weight' => '11',
            'page_num' => 2,
          ),
          13 => array(
            'nid' => 9782,
            'cid' => '13',
            'pid' => '0',
            'form_key' => 'add_on_feature',
            'name' => 'What Add on Feature is causing a problem',
            'type' => 'select',
            'value' => '',
            'extra' => array(
              'title_display' => 'before',
              'private' => 0,
              'aslist' => 0,
              'optrand' => 0,
              'conditional_component' => '5',
              'conditional_operator' => '=',
              'conditional_values' => '5',
              'other_option' => 1,
              'other_text' => 'Other...',
              'items' => "1|Dragon\n2|Scribe\n3|Inventory\n",
              'multiple' => 0,
              'custom_keys' => 0,
              'description' => '',
              'options_source' => '',
            ),
            'mandatory' => '1',
            'weight' => '12',
            'page_num' => 2,
          ),
          11 => array(
            'nid' => 9782,
            'cid' => '11',
            'pid' => '0',
            'form_key' => 'additional_notes',
            'name' => 'Please Enter any additional notes about the problem',
            'type' => 'textarea',
            'value' => '',
            'extra' => array(
              'title_display' => 0,
              'private' => 0,
              'resizable' => 1,
              'disabled' => 0,
              'conditional_component' => '1',
              'conditional_operator' => '=',
              'cols' => '',
              'rows' => '',
              'description' => '',
              'attributes' => array(),
              'conditional_values' => '',
            ),
            'mandatory' => '0',
            'weight' => '13',
            'page_num' => 2,
          ),
          15 => array(
            'nid' => 9782,
            'cid' => '15',
            'pid' => '0',
            'form_key' => 'screenshot',
            'name' => 'Screenshot Attachment',
            'type' => 'file',
            'value' => '',
            'extra' => array(
              'scheme' => 'public',
              'directory' => 'Training%20Department/trainer_install/screenshots',
              'title_display' => 'before',
              'private' => 0,
              'progress_indicator' => 'throbber',
              'filtering' => array(
                'size' => '5 MB',
                'types' => array(
                  'gif',
                  'jpg',
                  'png',
                  'pdf',
                  'doc',
                  'docx',
                  'ppt',
                  'pptx',
                  'zip',
                ),
                'addextensions' => '',
              ),
              'conditional_component' => '1',
              'conditional_operator' => '=',
              'description' => '',
              'attributes' => array(),
              'conditional_values' => '',
            ),
            'mandatory' => '0',
            'weight' => '14',
            'page_num' => 2,
          ),
        ),
      ),
      'cid' => '0',
      'last_comment_timestamp' => '1367251248',
      'last_comment_name' => NULL,
      'last_comment_uid' => '8',
      'comment_count' => '0',
      'print_display' => 0,
      'print_display_comment' => 0,
      'print_display_urllist' => 0,
      'name' => 'author',
      'picture' => '3001',
      'data' => 'a:22:{s:17:"fckeditor_default";s:1:"t";s:21:"fckeditor_show_toggle";s:1:"t";s:28:"fckeditor_show_fieldnamehint";s:1:"t";s:15:"fckeditor_popup";s:1:"f";s:14:"fckeditor_skin";s:10:"office2003";s:17:"fckeditor_toolbar";s:10:"DrupalFull";s:16:"fckeditor_expand";s:1:"t";s:15:"fckeditor_width";s:4:"100%";s:14:"fckeditor_lang";s:2:"en";s:19:"fckeditor_auto_lang";s:1:"t";s:8:"tac_lite";a:1:{i:5;a:1:{s:0:"";s:0:"";}}s:17:"tac_lite_scheme_2";a:1:{i:5;a:3:{i:124;s:3:"124";i:115;s:3:"115";i:71;s:2:"71";}}s:17:"tac_lite_scheme_3";a:1:{i:5;a:0:{}}s:7:"contact";i:1;s:15:"googleanalytics";a:1:{s:6:"custom";i:0;}s:14:"picture_delete";i:0;s:14:"picture_upload";s:0:"";s:16:"ckeditor_default";s:1:"t";s:20:"ckeditor_show_toggle";s:1:"t";s:14:"ckeditor_width";s:4:"100%";s:13:"ckeditor_lang";s:2:"en";s:18:"ckeditor_auto_lang";s:1:"t";}',
      'print_pdf_display' => 0,
      'print_pdf_display_comment' => 0,
      'print_pdf_display_urllist' => 0,
      'timestamp' => 1367519534,
      'path' => FALSE,
      'menu' => NULL,
      'node_export_drupal_version' => '7',
    ),
)
